name: Build Python
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
  pull_request:
jobs:
  build-python:
    strategy:
      fail-fast: false
      matrix:
        flavor: ["", "-wasmedge"]
        version: ["3.12.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Python
        run: make python/v${{ matrix.version }}${{ matrix.flavor }}
      - name: Upload python-${{ matrix.version }} assets
        uses: actions/upload-artifact@v3
        with:
          name: python-${{ matrix.version }}.zip
          path: |
            build-output/*.gz
            build-output/*.wasm
            build-output/*.txt
          if-no-files-found: error
